/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLBaseElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLBaseElement
{
    protected HTMLBaseElementImpl(nsIDOMHTMLBaseElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLBaseElementImpl getDOMInstance(nsIDOMHTMLBaseElement mozInst)
    {
        HTMLBaseElementImpl node = (HTMLBaseElementImpl) instances.get(mozInst);
        return node == null ? new HTMLBaseElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLBaseElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLBaseElement) moz;
    }
    
    public void setHref(String href)
    {
        getInstance().setHref(href);
    }
    
    public void setTarget(String target)
    {
        getInstance().setTarget(target);
    }
    
    public String getHref()
    {
        String result = getInstance().getHref();
        return result;
    }
    
    public String getTarget()
    {
        String result = getInstance().getTarget();
        return result;
    }
    
}
