/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLTableRowElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLTableRowElement
{
    protected HTMLTableRowElementImpl(nsIDOMHTMLTableRowElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLTableRowElementImpl getDOMInstance(nsIDOMHTMLTableRowElement mozInst)
    {
        HTMLTableRowElementImpl node = (HTMLTableRowElementImpl) instances.get(mozInst);
        return node == null ? new HTMLTableRowElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLTableRowElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLTableRowElement) moz;
    }
    
    public String getCh()
    {
        String result = getInstance().getCh();
        return result;
    }
    
    public void setCh(String ch)
    {
        getInstance().setCh(ch);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public void setChOff(String chOff)
    {
        getInstance().setChOff(chOff);
    }
    
    public String getChOff()
    {
        String result = getInstance().getChOff();
        return result;
    }
    
    public HTMLCollection getCells()
    {
        nsIDOMHTMLCollection result = getInstance().getCells();
        return new HTMLCollectionImpl(result);
    }
    
    public String getVAlign()
    {
        String result = getInstance().getVAlign();
        return result;
    }
    
    public HTMLElement insertCell(int index)
    {
        nsIDOMHTMLElement result = getInstance().insertCell(index);
        return (HTMLElement) NodeFactory.getNodeInstance(result);
    }
    
    public int getSectionRowIndex()
    {
        int result = getInstance().getSectionRowIndex();
        return result;
    }
    
    public void setVAlign(String vAlign)
    {
        getInstance().setVAlign(vAlign);
    }
    
    public void deleteCell(int index)
    {
        getInstance().deleteCell(index);
    }
    
    public String getBgColor()
    {
        String result = getInstance().getBgColor();
        return result;
    }
    
    public int getRowIndex()
    {
        int result = getInstance().getRowIndex();
        return result;
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setBgColor(String bgColor)
    {
        getInstance().setBgColor(bgColor);
    }
    
}
