/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLDirectoryElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLDirectoryElement
{
    protected HTMLDirectoryElementImpl(nsIDOMHTMLDirectoryElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLDirectoryElementImpl getDOMInstance(nsIDOMHTMLDirectoryElement mozInst)
    {
        HTMLDirectoryElementImpl node = (HTMLDirectoryElementImpl) instances.get(mozInst);
        return node == null ? new HTMLDirectoryElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLDirectoryElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLDirectoryElement) moz;
    }
    
    public boolean getCompact()
    {
        boolean result = getInstance().getCompact();
        return result;
    }
    
    public void setCompact(boolean compact)
    {
        getInstance().setCompact(compact);
    }
    
}
