/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLScriptElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLScriptElement
{
    protected HTMLScriptElementImpl(nsIDOMHTMLScriptElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLScriptElementImpl getDOMInstance(nsIDOMHTMLScriptElement mozInst)
    {
        HTMLScriptElementImpl node = (HTMLScriptElementImpl) instances.get(mozInst);
        return node == null ? new HTMLScriptElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLScriptElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLScriptElement) moz;
    }
    
    public String getCharset()
    {
        String result = getInstance().getCharset();
        return result;
    }
    
    public String getEvent()
    {
        String result = getInstance().getEvent();
        return result;
    }
    
    public void setCharset(String charset)
    {
        getInstance().setCharset(charset);
    }
    
    public String getSrc()
    {
        String result = getInstance().getSrc();
        return result;
    }
    
    public void setHtmlFor(String htmlFor)
    {
        getInstance().setHtmlFor(htmlFor);
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setDefer(boolean defer)
    {
        getInstance().setDefer(defer);
    }
    
    public String getText()
    {
        String result = getInstance().getText();
        return result;
    }
    
    public void setEvent(String event)
    {
        getInstance().setEvent(event);
    }
    
    public boolean getDefer()
    {
        boolean result = getInstance().getDefer();
        return result;
    }
    
    public void setSrc(String src)
    {
        getInstance().setSrc(src);
    }
    
    public void setText(String text)
    {
        getInstance().setText(text);
    }
    
    public String getHtmlFor()
    {
        String result = getInstance().getHtmlFor();
        return result;
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
