/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLFieldSetElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLFieldSetElement
{
    protected HTMLFieldSetElementImpl(nsIDOMHTMLFieldSetElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLFieldSetElementImpl getDOMInstance(nsIDOMHTMLFieldSetElement mozInst)
    {
        HTMLFieldSetElementImpl node = (HTMLFieldSetElementImpl) instances.get(mozInst);
        return node == null ? new HTMLFieldSetElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLFieldSetElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLFieldSetElement) moz;
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
}
