/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLOptGroupElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLOptGroupElement
{
    protected HTMLOptGroupElementImpl(nsIDOMHTMLOptGroupElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLOptGroupElementImpl getDOMInstance(nsIDOMHTMLOptGroupElement mozInst)
    {
        HTMLOptGroupElementImpl node = (HTMLOptGroupElementImpl) instances.get(mozInst);
        return node == null ? new HTMLOptGroupElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLOptGroupElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLOptGroupElement) moz;
    }
    
    public void setLabel(String label)
    {
        getInstance().setLabel(label);
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public String getLabel()
    {
        String result = getInstance().getLabel();
        return result;
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
}
