/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLHeadingElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLHeadingElement
{
    protected HTMLHeadingElementImpl(nsIDOMHTMLHeadingElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLHeadingElementImpl getDOMInstance(nsIDOMHTMLHeadingElement mozInst)
    {
        HTMLHeadingElementImpl node = (HTMLHeadingElementImpl) instances.get(mozInst);
        return node == null ? new HTMLHeadingElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLHeadingElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLHeadingElement) moz;
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
}
