/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLHeadElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLHeadElement
{
    protected HTMLHeadElementImpl(nsIDOMHTMLHeadElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLHeadElementImpl getDOMInstance(nsIDOMHTMLHeadElement mozInst)
    {
        HTMLHeadElementImpl node = (HTMLHeadElementImpl) instances.get(mozInst);
        return node == null ? new HTMLHeadElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLHeadElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLHeadElement) moz;
    }
    
    public String getProfile()
    {
        String result = getInstance().getProfile();
        return result;
    }
    
    public void setProfile(String profile)
    {
        getInstance().setProfile(profile);
    }
    
}
