/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLAppletElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLAppletElement
{
    protected HTMLAppletElementImpl(nsIDOMHTMLAppletElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLAppletElementImpl getDOMInstance(nsIDOMHTMLAppletElement mozInst)
    {
        HTMLAppletElementImpl node = (HTMLAppletElementImpl) instances.get(mozInst);
        return node == null ? new HTMLAppletElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLAppletElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLAppletElement) moz;
    }
    
    public String getObject()
    {
        String result = getInstance().getObject();
        return result;
    }
    
    public String getAlt()
    {
        String result = getInstance().getAlt();
        return result;
    }
    
    public void setWidth(String width)
    {
        getInstance().setWidth(width);
    }
    
    public void setObject(String object)
    {
        getInstance().setObject(object);
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public String getHeight()
    {
        String result = getInstance().getHeight();
        return result;
    }
    
    public String getCodeBase()
    {
        String result = getInstance().getCodeBase();
        return result;
    }
    
    public int getHspace()
    {
        return getInstance().getHspace();
    }
    
    public void setHeight(String height)
    {
        getInstance().setHeight(height);
    }
    
    public String getCode()
    {
        String result = getInstance().getCode();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public String getArchive()
    {
        String result = getInstance().getArchive();
        return result;
    }
    
    public int getVspace()
    {
        return getInstance().getVspace();
    }
    
    public void setCodeBase(String codeBase)
    {
        getInstance().setCodeBase(codeBase);
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setVspace(int vspace)
    {
        getInstance().setVspace(vspace);
    }
    
    public void setCode(String code)
    {
        getInstance().setCode(code);
    }
    
    public String getWidth()
    {
        String result = getInstance().getWidth();
        return result;
    }
    
    public void setArchive(String archive)
    {
        getInstance().setArchive(archive);
    }
    
    public void setHspace(int hspace)
    {
        getInstance().setHspace(hspace);
    }
    
    public void setAlt(String alt)
    {
        getInstance().setAlt(alt);
    }
    
}
