/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLImageElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLImageElement
{
    protected HTMLImageElementImpl(nsIDOMHTMLImageElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLImageElementImpl getDOMInstance(nsIDOMHTMLImageElement mozInst)
    {
        HTMLImageElementImpl node = (HTMLImageElementImpl) instances.get(mozInst);
        return node == null ? new HTMLImageElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLImageElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLImageElement) moz;
    }
    
    public void setIsMap(boolean isMap)
    {
        getInstance().setIsMap(isMap);
    }
    
    public int getWidth()
    {
        return getInstance().getWidth();
    }
    
    public String getAlt()
    {
        String result = getInstance().getAlt();
        return result;
    }
    
    public void setWidth(int width)
    {
        getInstance().setWidth(width);
    }
    
    public String getLowSrc()
    {

        throw new UnsupportedException();
    }
    
    public boolean getIsMap()
    {
        boolean result = getInstance().getIsMap();
        return result;
    }
    
    public void setLowSrc(String lowSrc)
    {

        throw new UnsupportedException();
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public int getHeight()
    {
        return getInstance().getHeight();
    }
    
    public void setHspace(int hspace)
    {
        getInstance().setHspace(hspace);
    }
    
    public void setLongDesc(String longDesc)
    {
        getInstance().setLongDesc(longDesc);
    }
    
    public int getHspace()
    {
        return getInstance().getHspace();
    }
    
    public void setSrc(String src)
    {
        getInstance().setSrc(src);
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public int getVspace()
    {
        return getInstance().getVspace();
    }
    
    public String getLongDesc()
    {
        String result = getInstance().getLongDesc();
        return result;
    }
    
    public void setUseMap(String useMap)
    {
        getInstance().setUseMap(useMap);
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setVspace(int vspace)
    {
        getInstance().setVspace(vspace);
    }
    
    public void setHeight(int height)
    {
        getInstance().setHeight(height);
    }
    
    public String getUseMap()
    {
        String result = getInstance().getUseMap();
        return result;
    }
    
    public String getSrc()
    {
        String result = getInstance().getSrc();
        return result;
    }
    
    public String getBorder()
    {
        String result = getInstance().getBorder();
        return result;
    }
    
    public void setBorder(String border)
    {
        getInstance().setBorder(border);
    }
    
    public void setAlt(String alt)
    {
        getInstance().setAlt(alt);
    }
    
}
