/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLTableColElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLTableColElement
{
    protected HTMLTableColElementImpl(nsIDOMHTMLTableColElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLTableColElementImpl getDOMInstance(nsIDOMHTMLTableColElement mozInst)
    {
        HTMLTableColElementImpl node = (HTMLTableColElementImpl) instances.get(mozInst);
        return node == null ? new HTMLTableColElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLTableColElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLTableColElement) moz;
    }
    
    public String getCh()
    {
        String result = getInstance().getCh();
        return result;
    }
    
    public int getSpan()
    {
        int result = getInstance().getSpan();
        return result;
    }
    
    public void setCh(String ch)
    {
        getInstance().setCh(ch);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public void setChOff(String chOff)
    {
        getInstance().setChOff(chOff);
    }
    
    public void setWidth(String width)
    {
        getInstance().setWidth(width);
    }
    
    public void setSpan(int span)
    {
        getInstance().setSpan(span);
    }
    
    public String getVAlign()
    {
        String result = getInstance().getVAlign();
        return result;
    }
    
    public String getWidth()
    {
        String result = getInstance().getWidth();
        return result;
    }
    
    public void setVAlign(String vAlign)
    {
        getInstance().setVAlign(vAlign);
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public String getChOff()
    {
        String result = getInstance().getChOff();
        return result;
    }
    
}
