/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLTextAreaElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLTextAreaElement
{
    protected HTMLTextAreaElementImpl(nsIDOMHTMLTextAreaElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLTextAreaElementImpl getDOMInstance(nsIDOMHTMLTextAreaElement mozInst)
    {
        HTMLTextAreaElementImpl node = (HTMLTextAreaElementImpl) instances.get(mozInst);
        return node == null ? new HTMLTextAreaElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLTextAreaElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLTextAreaElement) moz;
    }
    
    public void setRows(int rows)
    {
        getInstance().setRows(rows);
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
    public int getRows()
    {
        int result = getInstance().getRows();
        return result;
    }
    
    public void focus()
    {
        getInstance().focus();
    }
    
    public String getAccessKey()
    {
        String result = getInstance().getAccessKey();
        return result;
    }
    
    public void select()
    {
        getInstance().select();
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public boolean getReadOnly()
    {
        boolean result = getInstance().getReadOnly();
        return result;
    }
    
    public void blur()
    {
        getInstance().blur();
    }
    
    public void setTabIndex(int tabIndex)
    {
        getInstance().setTabIndex(tabIndex);
    }
    
    public void setValue(String value)
    {
        getInstance().setValue(value);
    }
    
    public String getDefaultValue()
    {
        String result = getInstance().getDefaultValue();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public void setDefaultValue(String defaultValue)
    {
        getInstance().setDefaultValue(defaultValue);
    }
    
    public int getCols()
    {
        int result = getInstance().getCols();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setAccessKey(String accessKey)
    {
        getInstance().setAccessKey(accessKey);
    }
    
    public int getTabIndex()
    {
        int result = getInstance().getTabIndex();
        return result;
    }
    
    public void setCols(int cols)
    {
        getInstance().setCols(cols);
    }
    
    public String getValue()
    {
        String result = getInstance().getValue();
        return result;
    }
    
    public void setReadOnly(boolean readOnly)
    {
        getInstance().setReadOnly(readOnly);
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
}
