/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLDivElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLDivElement
{
    protected HTMLDivElementImpl(nsIDOMHTMLDivElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLDivElementImpl getDOMInstance(nsIDOMHTMLDivElement mozInst)
    {
        HTMLDivElementImpl node = (HTMLDivElementImpl) instances.get(mozInst);
        return node == null ? new HTMLDivElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLDivElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLDivElement) moz;
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
}
