/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLStyleElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLStyleElement
{
    protected HTMLStyleElementImpl(nsIDOMHTMLStyleElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLStyleElementImpl getDOMInstance(nsIDOMHTMLStyleElement mozInst)
    {
        HTMLStyleElementImpl node = (HTMLStyleElementImpl) instances.get(mozInst);
        return node == null ? new HTMLStyleElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLStyleElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLStyleElement) moz;
    }
    
    public void setMedia(String media)
    {
        getInstance().setMedia(media);
    }
    
    public String getMedia()
    {
        String result = getInstance().getMedia();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
