/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLOptionElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLOptionElement
{
    protected HTMLOptionElementImpl(nsIDOMHTMLOptionElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLOptionElementImpl getDOMInstance(nsIDOMHTMLOptionElement mozInst)
    {
        HTMLOptionElementImpl node = (HTMLOptionElementImpl) instances.get(mozInst);
        return node == null ? new HTMLOptionElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLOptionElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLOptionElement) moz;
    }
    
    public int getIndex()
    {
        int result = getInstance().getIndex();
        return result;
    }
    
    public void setLabel(String label)
    {
        getInstance().setLabel(label);
    }
    
    public void setValue(String value)
    {
        getInstance().setValue(value);
    }
    
    public String getLabel()
    {
        String result = getInstance().getLabel();
        return result;
    }
    
    public void setSelected(boolean selected)
    {
        getInstance().setSelected(selected);
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
    public String getText()
    {
        String result = getInstance().getText();
        return result;
    }
    
    public String getValue()
    {
        String result = getInstance().getValue();
        return result;
    }
    
    public boolean getDefaultSelected()
    {
        boolean result = getInstance().getDefaultSelected();
        return result;
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public void setDefaultSelected(boolean defaultSelected)
    {
        getInstance().setDefaultSelected(defaultSelected);
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
    public boolean getSelected()
    {
        boolean result = getInstance().getSelected();
        return result;
    }
    
}
