/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLTableCellElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLTableCellElement
{
    protected HTMLTableCellElementImpl(nsIDOMHTMLTableCellElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLTableCellElementImpl getDOMInstance(nsIDOMHTMLTableCellElement mozInst)
    {
        HTMLTableCellElementImpl node = (HTMLTableCellElementImpl) instances.get(mozInst);
        return node == null ? new HTMLTableCellElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLTableCellElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLTableCellElement) moz;
    }
    
    public String getCh()
    {
        String result = getInstance().getCh();
        return result;
    }
    
    public String getScope()
    {
        String result = getInstance().getScope();
        return result;
    }
    
    public String getHeaders()
    {
        String result = getInstance().getHeaders();
        return result;
    }
    
    public void setScope(String scope)
    {
        getInstance().setScope(scope);
    }
    
    public void setWidth(String width)
    {
        getInstance().setWidth(width);
    }
    
    public String getAxis()
    {
        String result = getInstance().getAxis();
        return result;
    }
    
    public String getChOff()
    {
        String result = getInstance().getChOff();
        return result;
    }
    
    public String getHeight()
    {
        String result = getInstance().getHeight();
        return result;
    }
    
    public void setRowSpan(int rowSpan)
    {
        getInstance().setRowSpan(rowSpan);
    }
    
    public boolean getNoWrap()
    {
        boolean result = getInstance().getNoWrap();
        return result;
    }
    
    public String getAbbr()
    {
        String result = getInstance().getAbbr();
        return result;
    }
    
    public void setAbbr(String abbr)
    {
        getInstance().setAbbr(abbr);
    }
    
    public int getCellIndex()
    {
        int result = getInstance().getCellIndex();
        return result;
    }
    
    public void setBgColor(String bgColor)
    {
        getInstance().setBgColor(bgColor);
    }
    
    public void setColSpan(int colSpan)
    {
        getInstance().setColSpan(colSpan);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public void setChOff(String chOff)
    {
        getInstance().setChOff(chOff);
    }
    
    public void setVAlign(String vAlign)
    {
        getInstance().setVAlign(vAlign);
    }
    
    public void setNoWrap(boolean noWrap)
    {
        getInstance().setNoWrap(noWrap);
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setHeaders(String headers)
    {
        getInstance().setHeaders(headers);
    }
    
    public void setHeight(String height)
    {
        getInstance().setHeight(height);
    }
    
    public String getWidth()
    {
        String result = getInstance().getWidth();
        return result;
    }
    
    public void setCh(String ch)
    {
        getInstance().setCh(ch);
    }
    
    public String getVAlign()
    {
        String result = getInstance().getVAlign();
        return result;
    }
    
    public int getColSpan()
    {
        int result = getInstance().getColSpan();
        return result;
    }
    
    public int getRowSpan()
    {
        int result = getInstance().getRowSpan();
        return result;
    }
    
    public String getBgColor()
    {
        String result = getInstance().getBgColor();
        return result;
    }
    
    public void setAxis(String axis)
    {
        getInstance().setAxis(axis);
    }
    
}
