/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLUListElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLUListElement
{
    protected HTMLUListElementImpl(nsIDOMHTMLUListElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLUListElementImpl getDOMInstance(nsIDOMHTMLUListElement mozInst)
    {
        HTMLUListElementImpl node = (HTMLUListElementImpl) instances.get(mozInst);
        return node == null ? new HTMLUListElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLUListElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLUListElement) moz;
    }
    
    public boolean getCompact()
    {
        boolean result = getInstance().getCompact();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setCompact(boolean compact)
    {
        getInstance().setCompact(compact);
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
