/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLModElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLModElement
{
    protected HTMLModElementImpl(nsIDOMHTMLModElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLModElementImpl getDOMInstance(nsIDOMHTMLModElement mozInst)
    {
        HTMLModElementImpl node = (HTMLModElementImpl) instances.get(mozInst);
        return node == null ? new HTMLModElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLModElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLModElement) moz;
    }
    
    public String getDateTime()
    {
        String result = getInstance().getDateTime();
        return result;
    }
    
    public String getCite()
    {
        String result = getInstance().getCite();
        return result;
    }
    
    public void setDateTime(String dateTime)
    {
        getInstance().setDateTime(dateTime);
    }
    
    public void setCite(String cite)
    {
        getInstance().setCite(cite);
    }
    
}
