/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLLabelElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLLabelElement
{
    protected HTMLLabelElementImpl(nsIDOMHTMLLabelElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLLabelElementImpl getDOMInstance(nsIDOMHTMLLabelElement mozInst)
    {
        HTMLLabelElementImpl node = (HTMLLabelElementImpl) instances.get(mozInst);
        return node == null ? new HTMLLabelElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLLabelElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLLabelElement) moz;
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
    public void setHtmlFor(String htmlFor)
    {
        getInstance().setHtmlFor(htmlFor);
    }
    
    public String getAccessKey()
    {
        String result = getInstance().getAccessKey();
        return result;
    }
    
    public String getHtmlFor()
    {
        String result = getInstance().getHtmlFor();
        return result;
    }
    
    public void setAccessKey(String accessKey)
    {
        getInstance().setAccessKey(accessKey);
    }
    
}
