/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLElementImpl extends ElementImpl implements org.w3c.dom.html2.HTMLElement
{
    protected HTMLElementImpl(nsIDOMHTMLElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLElementImpl getDOMInstance(nsIDOMHTMLElement mozInst)
    {
        HTMLElementImpl node = (HTMLElementImpl) instances.get(mozInst);
        return node == null ? new HTMLElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLElement) moz;
    }
    
    public void setLang(String lang)
    {
        getInstance().setLang(lang);
    }
    
    public String getLang()
    {
        String result = getInstance().getLang();
        return result;
    }
    
    public void setTitle(String title)
    {
        getInstance().setTitle(title);
    }
    
    public String getDir()
    {
        String result = getInstance().getDir();
        return result;
    }
    
    public String getId()
    {
        String result = getInstance().getId();
        return result;
    }
    
    public void setClassName(String className)
    {
        getInstance().setClassName(className);
    }
    
    public String getTitle()
    {
        String result = getInstance().getTitle();
        return result;
    }
    
    public String getClassName()
    {
        String result = getInstance().getClassName();
        return result;
    }
    
    public void setId(String id)
    {
        getInstance().setId(id);
    }
    
    public void setDir(String dir)
    {
        getInstance().setDir(dir);
    }
    
}
