/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLAreaElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLAreaElement
{
    protected HTMLAreaElementImpl(nsIDOMHTMLAreaElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLAreaElementImpl getDOMInstance(nsIDOMHTMLAreaElement mozInst)
    {
        HTMLAreaElementImpl node = (HTMLAreaElementImpl) instances.get(mozInst);
        return node == null ? new HTMLAreaElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLAreaElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLAreaElement) moz;
    }
    
    public int getTabIndex()
    {
        int result = getInstance().getTabIndex();
        return result;
    }
    
    public String getAccessKey()
    {
        String result = getInstance().getAccessKey();
        return result;
    }
    
    public String getCoords()
    {
        String result = getInstance().getCoords();
        return result;
    }
    
    public void setTabIndex(int tabIndex)
    {
        getInstance().setTabIndex(tabIndex);
    }
    
    public void setShape(String shape)
    {
        getInstance().setShape(shape);
    }
    
    public String getShape()
    {
        String result = getInstance().getShape();
        return result;
    }
    
    public String getTarget()
    {
        String result = getInstance().getTarget();
        return result;
    }
    
    public void setAccessKey(String accessKey)
    {
        getInstance().setAccessKey(accessKey);
    }
    
    public void setHref(String href)
    {
        getInstance().setHref(href);
    }
    
    public String getAlt()
    {
        String result = getInstance().getAlt();
        return result;
    }
    
    public void setNoHref(boolean noHref)
    {
        getInstance().setNoHref(noHref);
    }
    
    public boolean getNoHref()
    {
        boolean result = getInstance().getNoHref();
        return result;
    }
    
    public void setCoords(String coords)
    {
        getInstance().setCoords(coords);
    }
    
    public String getHref()
    {
        String result = getInstance().getHref();
        return result;
    }
    
    public void setTarget(String target)
    {
        getInstance().setTarget(target);
    }
    
    public void setAlt(String alt)
    {
        getInstance().setAlt(alt);
    }
    
}
