/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLParamElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLParamElement
{
    protected HTMLParamElementImpl(nsIDOMHTMLParamElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLParamElementImpl getDOMInstance(nsIDOMHTMLParamElement mozInst)
    {
        HTMLParamElementImpl node = (HTMLParamElementImpl) instances.get(mozInst);
        return node == null ? new HTMLParamElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLParamElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLParamElement) moz;
    }
    
    public void setValue(String value)
    {
        getInstance().setValue(value);
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public String getValue()
    {
        String result = getInstance().getValue();
        return result;
    }
    
    public String getValueType()
    {
        String result = getInstance().getValueType();
        return result;
    }
    
    public void setValueType(String valueType)
    {
        getInstance().setValueType(valueType);
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
