/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLBodyElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLBodyElement
{
    protected HTMLBodyElementImpl(nsIDOMHTMLBodyElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLBodyElementImpl getDOMInstance(nsIDOMHTMLBodyElement mozInst)
    {
        HTMLBodyElementImpl node = (HTMLBodyElementImpl) instances.get(mozInst);
        return node == null ? new HTMLBodyElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLBodyElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLBodyElement) moz;
    }
    
    public String getALink()
    {
        String result = getInstance().getALink();
        return result;
    }
    
    public void setALink(String aLink)
    {
        getInstance().setALink(aLink);
    }
    
    public void setText(String text)
    {
        getInstance().setText(text);
    }
    
    public String getText()
    {
        String result = getInstance().getText();
        return result;
    }
    
    public void setBackground(String background)
    {
        getInstance().setBackground(background);
    }
    
    public String getLink()
    {
        String result = getInstance().getLink();
        return result;
    }
    
    public String getBackground()
    {
        String result = getInstance().getBackground();
        return result;
    }
    
    public void setVLink(String vLink)
    {
        getInstance().setVLink(vLink);
    }
    
    public void setLink(String link)
    {
        getInstance().setLink(link);
    }
    
    public String getBgColor()
    {
        String result = getInstance().getBgColor();
        return result;
    }
    
    public void setBgColor(String bgColor)
    {
        getInstance().setBgColor(bgColor);
    }
    
    public String getVLink()
    {
        String result = getInstance().getVLink();
        return result;
    }
    
}
