/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLTableSectionElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLTableSectionElement
{
    protected HTMLTableSectionElementImpl(nsIDOMHTMLTableSectionElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLTableSectionElementImpl getDOMInstance(nsIDOMHTMLTableSectionElement mozInst)
    {
        HTMLTableSectionElementImpl node = (HTMLTableSectionElementImpl) instances.get(mozInst);
        return node == null ? new HTMLTableSectionElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLTableSectionElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLTableSectionElement) moz;
    }
    
    public String getCh()
    {
        String result = getInstance().getCh();
        return result;
    }
    
    public void setCh(String ch)
    {
        getInstance().setCh(ch);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public void setChOff(String chOff)
    {
        getInstance().setChOff(chOff);
    }
    
    public HTMLCollection getRows()
    {
        nsIDOMHTMLCollection result = getInstance().getRows();
        return new HTMLCollectionImpl(result);
    }
    
    public String getVAlign()
    {
        String result = getInstance().getVAlign();
        return result;
    }
    
    public HTMLElement insertRow(int index)
    {
        nsIDOMHTMLElement result = getInstance().insertRow(index);
        return (HTMLElement) NodeFactory.getNodeInstance(result);
    }
    
    public void deleteRow(int index)
    {
        getInstance().deleteRow(index);
    }
    
    public void setVAlign(String vAlign)
    {
        getInstance().setVAlign(vAlign);
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public String getChOff()
    {
        String result = getInstance().getChOff();
        return result;
    }
    
}
