/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//org.w3c imports
import org.w3c.dom.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLCollectionImpl implements org.w3c.dom.html2.HTMLCollection
{
    protected nsIDOMHTMLCollection moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public HTMLCollectionImpl(nsIDOMHTMLCollection mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static HTMLCollectionImpl getDOMInstance(nsIDOMHTMLCollection mozInst)
    {
        HTMLCollectionImpl node = (HTMLCollectionImpl) instances.get(mozInst);
        return node == null ? new HTMLCollectionImpl(mozInst) : node;
    }
    
    public nsIDOMHTMLCollection getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public int getLength()
    {
        long result = getInstance().getLength();
        return (int) result;        
    }
    
    public Node namedItem(String name)
    {
        nsIDOMNode result = getInstance().namedItem(name);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node item(int index)
    {
        nsIDOMNode result = getInstance().item(index);
        return NodeFactory.getNodeInstance(result);
    }
    
}
