/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLHRElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLHRElement
{
    protected HTMLHRElementImpl(nsIDOMHTMLHRElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLHRElementImpl getDOMInstance(nsIDOMHTMLHRElement mozInst)
    {
        HTMLHRElementImpl node = (HTMLHRElementImpl) instances.get(mozInst);
        return node == null ? new HTMLHRElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLHRElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLHRElement) moz;
    }
    
    public String getWidth()
    {
        String result = getInstance().getWidth();
        return result;
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public void setWidth(String width)
    {
        getInstance().setWidth(width);
    }
    
    public boolean getNoShade()
    {
        boolean result = getInstance().getNoShade();
        return result;
    }
    
    public String getSize()
    {
        String result = getInstance().getSize();
        return result;
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setSize(String size)
    {
        getInstance().setSize(size);
    }
    
    public void setNoShade(boolean noShade)
    {
        getInstance().setNoShade(noShade);
    }
    
}
