/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLOListElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLOListElement
{
    protected HTMLOListElementImpl(nsIDOMHTMLOListElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLOListElementImpl getDOMInstance(nsIDOMHTMLOListElement mozInst)
    {
        HTMLOListElementImpl node = (HTMLOListElementImpl) instances.get(mozInst);
        return node == null ? new HTMLOListElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLOListElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLOListElement) moz;
    }
    
    public boolean getCompact()
    {
        boolean result = getInstance().getCompact();
        return result;
    }
    
    public int getStart()
    {
        int result = getInstance().getStart();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setCompact(boolean compact)
    {
        getInstance().setCompact(compact);
    }
    
    public void setStart(int start)
    {
        getInstance().setStart(start);
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
