/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLMapElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLMapElement
{
    protected HTMLMapElementImpl(nsIDOMHTMLMapElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLMapElementImpl getDOMInstance(nsIDOMHTMLMapElement mozInst)
    {
        HTMLMapElementImpl node = (HTMLMapElementImpl) instances.get(mozInst);
        return node == null ? new HTMLMapElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLMapElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLMapElement) moz;
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public HTMLCollection getAreas()
    {
        nsIDOMHTMLCollection result = getInstance().getAreas();
        return new HTMLCollectionImpl(result);
    }
    
}
