/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLFrameSetElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLFrameSetElement
{
    protected HTMLFrameSetElementImpl(nsIDOMHTMLFrameSetElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLFrameSetElementImpl getDOMInstance(nsIDOMHTMLFrameSetElement mozInst)
    {
        HTMLFrameSetElementImpl node = (HTMLFrameSetElementImpl) instances.get(mozInst);
        return node == null ? new HTMLFrameSetElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLFrameSetElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLFrameSetElement) moz;
    }
    
    public void setRows(String rows)
    {
        getInstance().setRows(rows);
    }
    
    public String getCols()
    {
        String result = getInstance().getCols();
        return result;
    }
    
    public String getRows()
    {
        String result = getInstance().getRows();
        return result;
    }
    
    public void setCols(String cols)
    {
        getInstance().setCols(cols);
    }
    
}
