/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//org.w3c imports
import org.w3c.dom.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLIFrameElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLIFrameElement
{
    protected HTMLIFrameElementImpl(nsIDOMHTMLIFrameElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLIFrameElementImpl getDOMInstance(nsIDOMHTMLIFrameElement mozInst)
    {
        HTMLIFrameElementImpl node = (HTMLIFrameElementImpl) instances.get(mozInst);
        return node == null ? new HTMLIFrameElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLIFrameElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLIFrameElement) moz;
    }
    
    public void setHeight(String height)
    {
        getInstance().setHeight(height);
    }
    
    public String getWidth()
    {
        String result = getInstance().getWidth();
        return result;
    }
    
    public Document getContentDocument()
    {
        nsIDOMDocument result = getInstance().getContentDocument();
        return (Document) NodeFactory.getNodeInstance(result);
    }
    
    public void setFrameBorder(String frameBorder)
    {
        getInstance().setFrameBorder(frameBorder);
    }
    
    public String getMarginHeight()
    {
        String result = getInstance().getMarginHeight();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public String getSrc()
    {
        String result = getInstance().getSrc();
        return result;
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public String getHeight()
    {
        String result = getInstance().getHeight();
        return result;
    }
    
    public void setSrc(String src)
    {
        getInstance().setSrc(src);
    }
    
    public void setMarginWidth(String marginWidth)
    {
        getInstance().setMarginWidth(marginWidth);
    }
    
    public String getLongDesc()
    {
        String result = getInstance().getLongDesc();
        return result;
    }
    
    public String getScrolling()
    {
        String result = getInstance().getScrolling();
        return result;
    }
    
    public void setScrolling(String scrolling)
    {
        getInstance().setScrolling(scrolling);
    }
    
    public void setMarginHeight(String marginHeight)
    {
        getInstance().setMarginHeight(marginHeight);
    }
    
    public String getMarginWidth()
    {
        String result = getInstance().getMarginWidth();
        return result;
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setWidth(String width)
    {
        getInstance().setWidth(width);
    }
    
    public void setLongDesc(String longDesc)
    {
        getInstance().setLongDesc(longDesc);
    }
    
    public String getFrameBorder()
    {
        String result = getInstance().getFrameBorder();
        return result;
    }
    
}
