/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLMenuElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLMenuElement
{
    protected HTMLMenuElementImpl(nsIDOMHTMLMenuElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLMenuElementImpl getDOMInstance(nsIDOMHTMLMenuElement mozInst)
    {
        HTMLMenuElementImpl node = (HTMLMenuElementImpl) instances.get(mozInst);
        return node == null ? new HTMLMenuElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLMenuElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLMenuElement) moz;
    }
    
    public boolean getCompact()
    {
        boolean result = getInstance().getCompact();
        return result;
    }
    
    public void setCompact(boolean compact)
    {
        getInstance().setCompact(compact);
    }
    
}
