/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLLIElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLLIElement
{
    protected HTMLLIElementImpl(nsIDOMHTMLLIElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLLIElementImpl getDOMInstance(nsIDOMHTMLLIElement mozInst)
    {
        HTMLLIElementImpl node = (HTMLLIElementImpl) instances.get(mozInst);
        return node == null ? new HTMLLIElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLLIElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLLIElement) moz;
    }
    
    public int getValue()
    {
        int result = getInstance().getValue();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setValue(int value)
    {
        getInstance().setValue(value);
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
