/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLIsIndexElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLIsIndexElement
{
    protected HTMLIsIndexElementImpl(nsIDOMHTMLIsIndexElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLIsIndexElementImpl getDOMInstance(nsIDOMHTMLIsIndexElement mozInst)
    {
        HTMLIsIndexElementImpl node = (HTMLIsIndexElementImpl) instances.get(mozInst);
        return node == null ? new HTMLIsIndexElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLIsIndexElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLIsIndexElement) moz;
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
    public void setPrompt(String prompt)
    {
        getInstance().setPrompt(prompt);
    }
    
    public String getPrompt()
    {
        String result = getInstance().getPrompt();
        return result;
    }
    
}
