/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLParagraphElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLParagraphElement
{
    protected HTMLParagraphElementImpl(nsIDOMHTMLParagraphElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLParagraphElementImpl getDOMInstance(nsIDOMHTMLParagraphElement mozInst)
    {
        HTMLParagraphElementImpl node = (HTMLParagraphElementImpl) instances.get(mozInst);
        return node == null ? new HTMLParagraphElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLParagraphElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLParagraphElement) moz;
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
}
