/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLInputElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLInputElement
{
    protected HTMLInputElementImpl(nsIDOMHTMLInputElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLInputElementImpl getDOMInstance(nsIDOMHTMLInputElement mozInst)
    {
        HTMLInputElementImpl node = (HTMLInputElementImpl) instances.get(mozInst);
        return node == null ? new HTMLInputElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLInputElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLInputElement) moz;
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
    public void focus()
    {
        getInstance().focus();
    }
    
    public int getSize()
    {
        return (int)getInstance().getSize();
    }
    
    public String getAlt()
    {
        String result = getInstance().getAlt();
        return result;
    }
    
    public boolean getDefaultChecked()
    {
        boolean result = getInstance().getDefaultChecked();
        return result;
    }
    
    public boolean getChecked()
    {
        boolean result = getInstance().getChecked();
        return result;
    }
    
    public void select()
    {
        getInstance().select();
    }
    
    public String getAccept()
    {
        String result = getInstance().getAccept();
        return result;
    }
    
    public void setValue(String value)
    {
        getInstance().setValue(value);
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public boolean getReadOnly()
    {
        boolean result = getInstance().getReadOnly();
        return result;
    }
    
    public void click()
    {
        getInstance().click();
    }
    
    public void setChecked(boolean checked)
    {
        getInstance().setChecked(checked);
    }
    
    public void setDefaultChecked(boolean defaultChecked)
    {
        getInstance().setDefaultChecked(defaultChecked);
    }
    
    public void setTabIndex(int tabIndex)
    {
        getInstance().setTabIndex(tabIndex);
    }
    
    public String getAccessKey()
    {
        String result = getInstance().getAccessKey();
        return result;
    }
    
    public void setSrc(String src)
    {
        getInstance().setSrc(src);
    }
    
    public String getDefaultValue()
    {
        String result = getInstance().getDefaultValue();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public void setAlign(String align)
    {
        getInstance().setAlign(align);
    }
    
    public void setDefaultValue(String defaultValue)
    {
        getInstance().setDefaultValue(defaultValue);
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setAccessKey(String accessKey)
    {
        getInstance().setAccessKey(accessKey);
    }
    
    public void setUseMap(String useMap)
    {
        getInstance().setUseMap(useMap);
    }
    
    public String getAlign()
    {
        String result = getInstance().getAlign();
        return result;
    }
    
    public int getTabIndex()
    {
        int result = getInstance().getTabIndex();
        return result;
    }
    
    public void setAccept(String accept)
    {
        getInstance().setAccept(accept);
    }
    
    public String getUseMap()
    {
        String result = getInstance().getUseMap();
        return result;
    }
    
    public int getMaxLength()
    {
        int result = getInstance().getMaxLength();
        return result;
    }
    
    public String getSrc()
    {
        String result = getInstance().getSrc();
        return result;
    }
    
    public String getValue()
    {
        String result = getInstance().getValue();
        return result;
    }
    
    public void setReadOnly(boolean readOnly)
    {
        getInstance().setReadOnly(readOnly);
    }
    
    public void setMaxLength(int maxLength)
    {
        getInstance().setMaxLength(maxLength);
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
    public void setSize(int size)
    {
        getInstance().setSize(size);
    }
    
    public void blur()
    {
        getInstance().blur();
    }
    
    public void setAlt(String alt)
    {
        getInstance().setAlt(alt);
    }

	public void setType(String type) {
		getInstance().setType(type);		
	}
    
}
