/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLBaseFontElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLBaseFontElement
{
    protected HTMLBaseFontElementImpl(nsIDOMHTMLBaseFontElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLBaseFontElementImpl getDOMInstance(nsIDOMHTMLBaseFontElement mozInst)
    {
        HTMLBaseFontElementImpl node = (HTMLBaseFontElementImpl) instances.get(mozInst);
        return node == null ? new HTMLBaseFontElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLBaseFontElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLBaseFontElement) moz;
    }
    
    public void setColor(String color)
    {
        getInstance().setColor(color);
    }
    
    public String getColor()
    {
        String result = getInstance().getColor();
        return result;
    }
    
    public void setFace(String face)
    {
        getInstance().setFace(face);
    }
    
    public int getSize()
    {
        return getInstance().getSize(); 
    }
    
    public String getFace()
    {
        String result = getInstance().getFace();
        return result;
    }
    
    public void setSize(int size)
    {
        getInstance().setSize(size);
    }
    
}
