/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLTitleElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLTitleElement
{
    protected HTMLTitleElementImpl(nsIDOMHTMLTitleElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLTitleElementImpl getDOMInstance(nsIDOMHTMLTitleElement mozInst)
    {
        HTMLTitleElementImpl node = (HTMLTitleElementImpl) instances.get(mozInst);
        return node == null ? new HTMLTitleElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLTitleElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLTitleElement) moz;
    }
    
    public void setText(String text)
    {
        getInstance().setText(text);
    }
    
    public String getText()
    {
        String result = getInstance().getText();
        return result;
    }
    
}
