/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

import org.w3c.dom.html2.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLButtonElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLButtonElement
{
    protected HTMLButtonElementImpl(nsIDOMHTMLButtonElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLButtonElementImpl getDOMInstance(nsIDOMHTMLButtonElement mozInst)
    {
        HTMLButtonElementImpl node = (HTMLButtonElementImpl) instances.get(mozInst);
        return node == null ? new HTMLButtonElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLButtonElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLButtonElement) moz;
    }
    
    public int getTabIndex()
    {
        int result = getInstance().getTabIndex();
        return result;
    }
    
    public String getAccessKey()
    {
        String result = getInstance().getAccessKey();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public HTMLFormElement getForm()
    {
        nsIDOMHTMLFormElement result = getInstance().getForm();
        return (HTMLFormElement) NodeFactory.getNodeInstance(result);
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public String getType()
    {

        throw new UnsupportedException();
    }
    
    public void setAccessKey(String accessKey)
    {
        getInstance().setAccessKey(accessKey);
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
    public String getValue()
    {
        String result = getInstance().getValue();
        return result;
    }
    
    public void setTabIndex(int tabIndex)
    {
        getInstance().setTabIndex(tabIndex);
    }
    
    public void setValue(String value)
    {
        getInstance().setValue(value);
    }
    
}
