/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//org.w3c imports
import org.w3c.dom.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLFrameElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLFrameElement
{
    protected HTMLFrameElementImpl(nsIDOMHTMLFrameElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLFrameElementImpl getDOMInstance(nsIDOMHTMLFrameElement mozInst)
    {
        HTMLFrameElementImpl node = (HTMLFrameElementImpl) instances.get(mozInst);
        return node == null ? new HTMLFrameElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLFrameElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLFrameElement) moz;
    }
    
    public Document getContentDocument()
    {
        nsIDOMDocument result = getInstance().getContentDocument();
        return (Document) NodeFactory.getNodeInstance(result);
    }
    
    public String getMarginHeight()
    {
        String result = getInstance().getMarginHeight();
        return result;
    }
    
    public void setName(String name)
    {
        getInstance().setName(name);
    }
    
    public String getSrc()
    {
        String result = getInstance().getSrc();
        return result;
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public void setSrc(String src)
    {
        getInstance().setSrc(src);
    }
    
    public void setMarginWidth(String marginWidth)
    {
        getInstance().setMarginWidth(marginWidth);
    }
    
    public String getLongDesc()
    {
        String result = getInstance().getLongDesc();
        return result;
    }
    
    public String getScrolling()
    {
        String result = getInstance().getScrolling();
        return result;
    }
    
    public void setNoResize(boolean noResize)
    {
        getInstance().setNoResize(noResize);
    }
    
    public void setScrolling(String scrolling)
    {
        getInstance().setScrolling(scrolling);
    }
    
    public void setMarginHeight(String marginHeight)
    {
        getInstance().setMarginHeight(marginHeight);
    }
    
    public String getMarginWidth()
    {
        String result = getInstance().getMarginWidth();
        return result;
    }
    
    public void setFrameBorder(String frameBorder)
    {
        getInstance().setFrameBorder(frameBorder);
    }
    
    public boolean getNoResize()
    {
        boolean result = getInstance().getNoResize();
        return result;
    }
    
    public void setLongDesc(String longDesc)
    {
        getInstance().setLongDesc(longDesc);
    }
    
    public String getFrameBorder()
    {
        String result = getInstance().getFrameBorder();
        return result;
    }
    
}
