/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLLinkElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLLinkElement
{
    protected HTMLLinkElementImpl(nsIDOMHTMLLinkElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLLinkElementImpl getDOMInstance(nsIDOMHTMLLinkElement mozInst)
    {
        HTMLLinkElementImpl node = (HTMLLinkElementImpl) instances.get(mozInst);
        return node == null ? new HTMLLinkElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLLinkElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLLinkElement) moz;
    }
    
    public String getCharset()
    {
        String result = getInstance().getCharset();
        return result;
    }
    
    public String getType()
    {
        String result = getInstance().getType();
        return result;
    }
    
    public void setMedia(String media)
    {
        getInstance().setMedia(media);
    }
    
    public void setCharset(String charset)
    {
        getInstance().setCharset(charset);
    }
    
    public String getHreflang()
    {
        String result = getInstance().getHreflang();
        return result;
    }
    
    public void setRev(String rev)
    {
        getInstance().setRev(rev);
    }
    
    public void setTarget(String target)
    {
        getInstance().setTarget(target);
    }
    
    public String getRel()
    {
        String result = getInstance().getRel();
        return result;
    }
    
    public void setHreflang(String hreflang)
    {
        getInstance().setHreflang(hreflang);
    }
    
    public String getRev()
    {
        String result = getInstance().getRev();
        return result;
    }
    
    public String getTarget()
    {
        String result = getInstance().getTarget();
        return result;
    }
    
    public void setHref(String href)
    {
        getInstance().setHref(href);
    }
    
    public String getMedia()
    {
        String result = getInstance().getMedia();
        return result;
    }
    
    public void setDisabled(boolean disabled)
    {
        getInstance().setDisabled(disabled);
    }
    
    public boolean getDisabled()
    {
        boolean result = getInstance().getDisabled();
        return result;
    }
    
    public void setRel(String rel)
    {
        getInstance().setRel(rel);
    }
    
    public String getHref()
    {
        String result = getInstance().getHref();
        return result;
    }
    
    public void setType(String type)
    {
        getInstance().setType(type);
    }
    
}
