/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.html;

//XPCOM import
import org.mozilla.interfaces.*;


public class HTMLFontElementImpl extends HTMLElementImpl implements org.w3c.dom.html2.HTMLFontElement
{
    protected HTMLFontElementImpl(nsIDOMHTMLFontElement mozInst)
    {
        super( mozInst );
    }

    public static HTMLFontElementImpl getDOMInstance(nsIDOMHTMLFontElement mozInst)
    {
        HTMLFontElementImpl node = (HTMLFontElementImpl) instances.get(mozInst);
        return node == null ? new HTMLFontElementImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMHTMLFontElement getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMHTMLFontElement) moz;
    }
    
    public void setColor(String color)
    {
        getInstance().setColor(color);
    }
    
    public String getColor()
    {
        String result = getInstance().getColor();
        return result;
    }
    
    public void setFace(String face)
    {
        getInstance().setFace(face);
    }
    
    public String getSize()
    {
        String result = getInstance().getSize();
        return result;
    }
    
    public String getFace()
    {
        String result = getInstance().getFace();
        return result;
    }
    
    public void setSize(String size)
    {
        getInstance().setSize(size);
    }
    
}
