/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.traversal;

//org.w3c imports
import org.w3c.dom.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class NodeFilterImpl implements org.w3c.dom.traversal.NodeFilter
{
    protected nsIDOMNodeFilter moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public NodeFilterImpl(nsIDOMNodeFilter mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static NodeFilterImpl getDOMInstance(nsIDOMNodeFilter mozInst)
    {
        NodeFilterImpl node = (NodeFilterImpl) instances.get(mozInst);
        return node == null ? new NodeFilterImpl(mozInst) : node;
    }
    
    public nsIDOMNodeFilter getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public short acceptNode(Node n)
    {
        nsIDOMNode mozN = ((NodeImpl) n).getInstance();
        short result = getInstance().acceptNode(mozN);
        return result;
    }
    
}
