/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.traversal;

//org.w3c imports
import org.w3c.dom.*;
import org.w3c.dom.traversal.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class TreeWalkerImpl implements org.w3c.dom.traversal.TreeWalker
{
    protected nsIDOMTreeWalker moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public TreeWalkerImpl(nsIDOMTreeWalker mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static TreeWalkerImpl getDOMInstance(nsIDOMTreeWalker mozInst)
    {
        TreeWalkerImpl node = (TreeWalkerImpl) instances.get(mozInst);
        return node == null ? new TreeWalkerImpl(mozInst) : node;
    }
    
    public nsIDOMTreeWalker getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public void setCurrentNode(Node currentNode)
    {
        nsIDOMNode mozCurrentnode = ((NodeImpl) currentNode).getInstance();
        getInstance().setCurrentNode(mozCurrentnode);
    }
    
    public NodeFilter getFilter()
    {
        nsIDOMNodeFilter result = getInstance().getFilter();
        return new NodeFilterImpl(result);
    }
    
    public Node nextNode()
    {
        nsIDOMNode result = getInstance().nextNode();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node nextSibling()
    {
        nsIDOMNode result = getInstance().nextSibling();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node parentNode()
    {
        nsIDOMNode result = getInstance().parentNode();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node firstChild()
    {
        nsIDOMNode result = getInstance().firstChild();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node getRoot()
    {
        nsIDOMNode result = getInstance().getRoot();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node getCurrentNode()
    {
        nsIDOMNode result = getInstance().getCurrentNode();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node previousNode()
    {
        nsIDOMNode result = getInstance().previousNode();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node lastChild()
    {
        nsIDOMNode result = getInstance().lastChild();
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node previousSibling()
    {
        nsIDOMNode result = getInstance().previousSibling();
        return NodeFactory.getNodeInstance(result);
    }
    
    public boolean getExpandEntityReferences()
    {
        boolean result = getInstance().getExpandEntityReferences();
        return result;
    }
    
    public int getWhatToShow()
    {
        long result = getInstance().getWhatToShow();
        return (int) result;        
    }
    
}
