/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.events;

//org.w3c imports
import org.w3c.dom.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class MutationEventImpl extends EventImpl implements org.w3c.dom.events.MutationEvent
{
    protected MutationEventImpl(nsIDOMMutationEvent mozInst)
    {
        super( mozInst );
    }

    public static MutationEventImpl getDOMInstance(nsIDOMMutationEvent mozInst)
    {
        MutationEventImpl node = (MutationEventImpl) instances.get(mozInst);
        return node == null ? new MutationEventImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMMutationEvent getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMMutationEvent) moz;
    }
    
    public Node getRelatedNode()
    {
        nsIDOMNode result = getInstance().getRelatedNode();
        return NodeFactory.getNodeInstance(result);
    }
    
    public void initMutationEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Node relatedNodeArg, String prevValueArg, String newValueArg, String attrNameArg, short attrChangeArg)
    {
        nsIDOMNode mozRelatednodearg = ((NodeImpl) relatedNodeArg).getInstance();
        getInstance().initMutationEvent(typeArg, canBubbleArg, cancelableArg, mozRelatednodearg, prevValueArg, newValueArg, attrNameArg, attrChangeArg);
    }
    
    public String getPrevValue()
    {
        String result = getInstance().getPrevValue();
        return result;
    }
    
    public short getAttrChange()
    {
        int result = getInstance().getAttrChange();
        return (short) result;
    }
    
    public String getNewValue()
    {
        String result = getInstance().getNewValue();
        return result;
    }
    
    public String getAttrName()
    {
        String result = getInstance().getAttrName();
        return result;
    }
    
}
