/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.events;

import org.w3c.dom.events.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class EventListenerImpl implements org.w3c.dom.events.EventListener
{
    protected nsIDOMEventListener moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public EventListenerImpl(nsIDOMEventListener mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static EventListenerImpl getDOMInstance(nsIDOMEventListener mozInst)
    {
        EventListenerImpl node = (EventListenerImpl) instances.get(mozInst);
        return node == null ? new EventListenerImpl(mozInst) : node;
    }
    
    public nsIDOMEventListener getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public void handleEvent(Event evt)
    {
        nsIDOMEvent mozEvt = ((EventImpl) evt).getInstance();
        getInstance().handleEvent(mozEvt);
    }
    
    
    
}
