/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.events;

import org.w3c.dom.views.*;

import org.mozilla.dom.views.*;

//XPCOM import
import org.mozilla.interfaces.*;


public class KeyEventImpl extends UIEventImpl /*implements org.w3c.dom.events.KeyEvent*/
{
    protected KeyEventImpl(nsIDOMKeyEvent mozInst)
    {
        super( mozInst );
    }

    public static KeyEventImpl getDOMInstance(nsIDOMKeyEvent mozInst)
    {
        KeyEventImpl node = (KeyEventImpl) instances.get(mozInst);
        return node == null ? new KeyEventImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMKeyEvent getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMKeyEvent) moz;
    }
    
    public long getCharCode()
    {
        long result = getInstance().getCharCode();
        return result;
    }
    
    public boolean getMetaKey()
    {
        boolean result = getInstance().getMetaKey();
        return result;
    }
    
    public boolean getCtrlKey()
    {
        boolean result = getInstance().getCtrlKey();
        return result;
    }
    
    public boolean getShiftKey()
    {
        boolean result = getInstance().getShiftKey();
        return result;
    }
    
    public boolean getAltKey()
    {
        boolean result = getInstance().getAltKey();
        return result;
    }
    
    public long getKeyCode()
    {
        long result = getInstance().getKeyCode();
        return result;
    }
    
    public void initKeyEvent(String arg1, boolean arg2, boolean arg3, AbstractView arg4, boolean arg5, boolean arg6, boolean arg7, boolean arg8, long arg9, long arg10)
    {
        nsIDOMAbstractView mozArg4 = ((AbstractViewImpl) arg4).getInstance();
        getInstance().initKeyEvent(arg1, arg2, arg3, mozArg4, arg5, arg6, arg7, arg8, arg9, arg10);
    }
    
}
