/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;


import org.mozilla.interfaces.*;
//XPCOM import


public class CharacterDataImpl extends NodeImpl implements org.w3c.dom.CharacterData
{
    protected CharacterDataImpl(nsIDOMCharacterData mozInst)
    {
        super( mozInst );
    }

    public static CharacterDataImpl getDOMInstance(nsIDOMCharacterData mozInst)
    {
        CharacterDataImpl node = (CharacterDataImpl) instances.get(mozInst);
        return node == null ? new CharacterDataImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMCharacterData getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMCharacterData) moz;
    }
    
    public void deleteData(int offset, int count)
    {
        getInstance().deleteData(offset, count);
    }
    
    public int getLength()
    {
        long result = getInstance().getLength();
        return (int) result;        
    }
    
    public void replaceData(int offset, int count, String arg)
    {
        getInstance().replaceData(offset, count, arg);
    }
    
    public void insertData(int offset, String arg)
    {
        getInstance().insertData(offset, arg);
    }
    
    public void appendData(String arg)
    {
        getInstance().appendData(arg);
    }
    
    public String getData()
    {
        String result = getInstance().getData();
        return result;
    }
    
    public String substringData(int offset, int count)
    {
        String result = getInstance().substringData(offset, count);
        return result;
    }
    
    public void setData(String data)
    {
        getInstance().setData(data);
    }
    
}
