/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;


import org.mozilla.interfaces.*;
//XPCOM import


public class CommentImpl extends CharacterDataImpl implements org.w3c.dom.Comment
{
    protected CommentImpl(nsIDOMComment mozInst)
    {
        super( mozInst );
    }

    public static CommentImpl getDOMInstance(nsIDOMComment mozInst)
    {
        CommentImpl node = (CommentImpl) instances.get(mozInst);
        return node == null ? new CommentImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMComment getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMComment) moz;
    }
    
}
