/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//XPCOM import
import org.mozilla.interfaces.*;


public class DOMStringListImpl implements org.w3c.dom.DOMStringList
{
    protected nsIDOMDOMStringList moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public DOMStringListImpl(nsIDOMDOMStringList mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static DOMStringListImpl getDOMInstance(nsIDOMDOMStringList mozInst)
    {
        DOMStringListImpl node = (DOMStringListImpl) instances.get(mozInst);
        return node == null ? new DOMStringListImpl(mozInst) : node;
    }
    
    public nsIDOMDOMStringList getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public String item(int index)
    {
        String result = getInstance().item(index);
        return result;
    }
    
    public boolean contains(String str)
    {

        throw new UnsupportedException();
    }
    
    public int getLength()
    {
        long result = getInstance().getLength();
        return (int) result;        
    }
    
}
