/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//XPCOM import

import org.mozilla.interfaces.*;


public class EntityImpl extends NodeImpl implements org.w3c.dom.Entity
{
    protected EntityImpl(nsIDOMEntity mozInst)
    {
        super( mozInst );
    }

    public static EntityImpl getDOMInstance(nsIDOMEntity mozInst)
    {
        EntityImpl node = (EntityImpl) instances.get(mozInst);
        return node == null ? new EntityImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMEntity getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMEntity) moz;
    }
    
    public String getPublicId()
    {
        String result = getInstance().getPublicId();
        return result;
    }
    
    public String getXmlEncoding()
    {

        throw new UnsupportedException();
    }
    
    public String getXmlVersion()
    {

        throw new UnsupportedException();
    }
    
    public String getSystemId()
    {
        String result = getInstance().getSystemId();
        return result;
    }
    
    public String getInputEncoding()
    {

        throw new UnsupportedException();
    }
    
    public String getNotationName()
    {
        String result = getInstance().getNotationName();
        return result;
    }
    
}
