/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

import org.mozilla.interfaces.*;
//XPCOM import


public class NotationImpl extends NodeImpl implements org.w3c.dom.Notation
{
    protected NotationImpl(nsIDOMNotation mozInst)
    {
        super( mozInst );
    }

    public static NotationImpl getDOMInstance(nsIDOMNotation mozInst)
    {
        NotationImpl node = (NotationImpl) instances.get(mozInst);
        return node == null ? new NotationImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMNotation getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMNotation) moz;
    }
    
    public String getSystemId()
    {
        String result = getInstance().getSystemId();
        return result;
    }
    
    public String getPublicId()
    {
        String result = getInstance().getPublicId();
        return result;
    }
    
}
