/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

import org.mozilla.interfaces.*;
//XPCOM import


public class ProcessingInstructionImpl extends NodeImpl implements org.w3c.dom.ProcessingInstruction
{
    protected ProcessingInstructionImpl(nsIDOMProcessingInstruction mozInst)
    {
        super( mozInst );
    }

    public static ProcessingInstructionImpl getDOMInstance(nsIDOMProcessingInstruction mozInst)
    {
        ProcessingInstructionImpl node = (ProcessingInstructionImpl) instances.get(mozInst);
        return node == null ? new ProcessingInstructionImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMProcessingInstruction getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMProcessingInstruction) moz;
    }
    
    public String getData()
    {
        String result = getInstance().getData();
        return result;
    }
    
    public String getTarget()
    {
        String result = getInstance().getTarget();
        return result;
    }
    
    public void setData(String data)
    {
        getInstance().setData(data);
    }
    
}
