/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//org.w3c imports
import org.w3c.dom.Text;
import org.mozilla.interfaces.*;


public class TextImpl extends CharacterDataImpl implements org.w3c.dom.Text
{
    protected TextImpl(nsIDOMText mozInst)
    {
        super( mozInst );
    }

    public static TextImpl getDOMInstance(nsIDOMText mozInst)
    {
        TextImpl node = (TextImpl) instances.get(mozInst);
        return node == null ? new TextImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMText getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMText) moz;
    }
    
    public String getWholeText()
    {

        throw new UnsupportedException();
    }
    
    public boolean isElementContentWhitespace()
    {

        throw new UnsupportedException();
    }
    
    public Text replaceWholeText(String content)
    {

        throw new UnsupportedException();
    }
    
    public Text splitText(int offset)
    {
        nsIDOMText result = getInstance().splitText(offset);
        return (Text) NodeFactory.getNodeInstance(result);
    }
    
}
