/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//org.w3c imports
import org.mozilla.interfaces.*;
import org.w3c.dom.Element;
import org.w3c.dom.TypeInfo;


public class AttrImpl extends NodeImpl implements org.w3c.dom.Attr
{
    protected AttrImpl(nsIDOMAttr mozInst)
    {
        super( mozInst );
    }

    public static AttrImpl getDOMInstance(nsIDOMAttr mozInst)
    {
        AttrImpl node = (AttrImpl) instances.get(mozInst);
        return node == null ? new AttrImpl(mozInst) : node;
    }
    
    @Override
	public nsIDOMAttr getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return (nsIDOMAttr) moz;
    }
    
    public void setValue(String value)
    {
        getInstance().setValue(value);
    }
    
    public boolean getSpecified()
    {
        boolean result = getInstance().getSpecified();
        return result;
    }
    
    public TypeInfo getSchemaTypeInfo()
    {

        throw new UnsupportedException();
    }
    
    public String getName()
    {
        String result = getInstance().getName();
        return result;
    }
    
    public String getValue()
    {
        String result = getInstance().getValue();
        return result;
    }
    
    public Element getOwnerElement()
    {
        nsIDOMElement result = getInstance().getOwnerElement();
        return (Element) NodeFactory.getNodeInstance(result);
    }
    
    public boolean isId()
    {

        throw new UnsupportedException();
    }
    
}
