/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//org.w3c imports
import org.w3c.dom.DOMStringList;
import org.mozilla.interfaces.*;

public class DOMConfigurationImpl implements org.w3c.dom.DOMConfiguration
{
    protected nsIDOMDOMConfiguration moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public DOMConfigurationImpl(nsIDOMDOMConfiguration mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static DOMConfigurationImpl getDOMInstance(nsIDOMDOMConfiguration mozInst)
    {
        DOMConfigurationImpl node = (DOMConfigurationImpl) instances.get(mozInst);
        return node == null ? new DOMConfigurationImpl(mozInst) : node;
    }
    
    public nsIDOMDOMConfiguration getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public boolean canSetParameter(String name, Object value)
    {
        nsIVariant casted_value = (nsIVariant) value;
        boolean result = getInstance().canSetParameter(name, casted_value);
        return result;
    }
    
    public void setParameter(String name, Object value)
    {
        nsIVariant casted_value = (nsIVariant) value;
        getInstance().setParameter(name, casted_value);
    }
    
    public DOMStringList getParameterNames()
    {

        throw new UnsupportedException();
    }
    
    public Object getParameter(String name)
    {
        nsIVariant result = getInstance().getParameter(name);
        return result;
    }
    
}
