/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//org.w3c imports
import org.w3c.dom.Node;
import org.mozilla.interfaces.*;


public class NamedNodeMapImpl implements org.w3c.dom.NamedNodeMap
{
    protected nsIDOMNamedNodeMap moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public NamedNodeMapImpl(nsIDOMNamedNodeMap mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static NamedNodeMapImpl getDOMInstance(nsIDOMNamedNodeMap mozInst)
    {
        NamedNodeMapImpl node = (NamedNodeMapImpl) instances.get(mozInst);
        return node == null ? new NamedNodeMapImpl(mozInst) : node;
    }
    
    public nsIDOMNamedNodeMap getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public Node removeNamedItemNS(String namespaceURI, String localName)
    {
        nsIDOMNode result = getInstance().removeNamedItemNS(namespaceURI, localName);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node setNamedItemNS(Node arg)
    {
        nsIDOMNode mozArg = ((NodeImpl) arg).getInstance();
        nsIDOMNode result = getInstance().setNamedItemNS(mozArg);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node getNamedItemNS(String namespaceURI, String localName)
    {
        nsIDOMNode result = getInstance().getNamedItemNS(namespaceURI, localName);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node getNamedItem(String name)
    {
        nsIDOMNode result = getInstance().getNamedItem(name);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node setNamedItem(Node arg)
    {
        nsIDOMNode mozArg = ((NodeImpl) arg).getInstance();
        nsIDOMNode result = getInstance().setNamedItem(mozArg);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node item(int index)
    {
        nsIDOMNode result = getInstance().item(index);
        return NodeFactory.getNodeInstance(result);
    }
    
    public Node removeNamedItem(String name)
    {
        nsIDOMNode result = getInstance().removeNamedItem(name);
        return NodeFactory.getNodeInstance(result);
    }
    
    public int getLength()
    {
        long result = getInstance().getLength();
        return (int) result;        
    }
    
}
