/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//org.w3c imports
import org.w3c.dom.Node;
import org.mozilla.interfaces.*;


public class NodeListImpl implements org.w3c.dom.NodeList
{
    protected nsIDOMNodeList moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public NodeListImpl(nsIDOMNodeList mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static NodeListImpl getDOMInstance(nsIDOMNodeList mozInst)
    {
        NodeListImpl node = (NodeListImpl) instances.get(mozInst);
        return node == null ? new NodeListImpl(mozInst) : node;
    }
    
    public nsIDOMNodeList getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public Node item(int index)
    {
        nsIDOMNode result = getInstance().item(index);
        return NodeFactory.getNodeInstance(result);
    }
    
    public int getLength()
    {
        long result = getInstance().getLength();
        return (int) result;        
    }
    
}
