/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom;

//org.w3c imports
import org.w3c.dom.Node;

import org.mozilla.interfaces.*;


public class UserDataHandlerImpl implements org.w3c.dom.UserDataHandler
{
    protected nsIDOMUserDataHandler moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public UserDataHandlerImpl(nsIDOMUserDataHandler mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static UserDataHandlerImpl getDOMInstance(nsIDOMUserDataHandler mozInst)
    {
        UserDataHandlerImpl node = (UserDataHandlerImpl) instances.get(mozInst);
        return node == null ? new UserDataHandlerImpl(mozInst) : node;
    }
    
    public nsIDOMUserDataHandler getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public void handle(short operation, String key, Object data, Node src, Node dst)
    {
        nsIDOMNode mozSrc = ((NodeImpl) src).getInstance();
        nsIDOMNode mozDst = ((NodeImpl) dst).getInstance();
        nsIVariant casted_data = (nsIVariant) data;
        getInstance().handle(operation, key, casted_data, mozSrc, mozDst);
    }
    
}
