/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.views;

import org.w3c.dom.views.*;

//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class DocumentViewImpl implements org.w3c.dom.views.DocumentView
{
    protected nsIDOMDocumentView moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public DocumentViewImpl(nsIDOMDocumentView mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static DocumentViewImpl getDOMInstance(nsIDOMDocumentView mozInst)
    {
        DocumentViewImpl node = (DocumentViewImpl) instances.get(mozInst);
        return node == null ? new DocumentViewImpl(mozInst) : node;
    }
    
    public nsIDOMDocumentView getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public AbstractView getDefaultView()
    {
        nsIDOMAbstractView result = getInstance().getDefaultView();
        return new AbstractViewImpl(result);
    }
    
}
