/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.ranges;

import org.w3c.dom.ranges.*;
//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class DocumentRangeImpl implements org.w3c.dom.ranges.DocumentRange
{
    protected nsIDOMDocumentRange moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public DocumentRangeImpl(nsIDOMDocumentRange mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static DocumentRangeImpl getDOMInstance(nsIDOMDocumentRange mozInst)
    {
        DocumentRangeImpl node = (DocumentRangeImpl) instances.get(mozInst);
        return node == null ? new DocumentRangeImpl(mozInst) : node;
    }
    
    public nsIDOMDocumentRange getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public Range createRange()
    {
        nsIDOMRange result = getInstance().createRange();
        return new RangeImpl(result);
    }
    
}
