/*
+-----------------------------------------------+
| do NOT edit this file!                        |
+-----------------------------------------------+
| This file is an auto-generated implementation | 
| of the coresponding org.w3c.dom interface via |
| Java-XPCOM                                    |
| (c)2005, Peter Szinek [peter@rt.sk]           |
+-----------------------------------------------+
*/


package org.mozilla.dom.views;

import org.w3c.dom.views.*;

//com.lixto imports
import org.mozilla.dom.*;
//XPCOM import
import org.mozilla.interfaces.*;


public class AbstractViewImpl implements org.w3c.dom.views.AbstractView
{
    protected nsIDOMAbstractView moz;
    protected static WeakValueHashMap instances = new WeakValueHashMap();
    
    public AbstractViewImpl(nsIDOMAbstractView mozInst)
    {
        moz = mozInst;
        instances.put(mozInst, this);
    }    

    public static AbstractViewImpl getDOMInstance(nsIDOMAbstractView mozInst)
    {
        AbstractViewImpl node = (AbstractViewImpl) instances.get(mozInst);
        return node == null ? new AbstractViewImpl(mozInst) : node;
    }
    
    public nsIDOMAbstractView getInstance()
    {
        //This was already queryinterfaced, so safe to cast
        return moz;
    }
    
    public DocumentView getDocument()
    {
        nsIDOMDocumentView result = getInstance().getDocument();
        return new DocumentViewImpl(result);
    }
    
}
